version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: staff-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: staff_management
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: staff-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: staff_management
    depends_on:
      - postgres
    restart: unless-stopped

  hr-staff:
    build:
      context: ./HR-staff
    container_name: hr-staff
    ports:
      - "6701:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
